### PR TITLE
Fix undo of moving

### LINKED ISSUE #55: Undo-redo of moving elements is broken
When you try to undo any move operation, the element goes straight to (0,0).

### PR DESCRIPTION
**Pull request by LChernigovskaya**
Fix #55

### CODE REVIEW

File: editor-core/src/main/webapp/app/core/editorCore/controller/SceneController.ts [hunk 1]
```diff
@@ -240,30 +240,28 @@ class SceneController {
...
+            var node:DiagramNode = this.scene.getNodeById(cellView.model.id);
+            this.lastCellMouseDownPosition.x = node.getX();
+            this.lastCellMouseDownPosition.y = node.getY();
         }
 
     }
 
     private cellPointerupListener(cellView, event, x, y): void {
-        if ((this.clickFlag) && (event.button == 2)) {
+        if (this.clickFlag && event.button == 2) {
```
Comment (jzuken) [inline editor-core/src/main/webapp/app/core/editorCore/controller/SceneController.ts]: I guess these button values would look better in a enum :)

**Review by jzuken — CHANGES_REQUESTED** [review]
